# Generated by Django 4.1.4 on 2022-12-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0003_application"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="experience",
            field=models.CharField(
                choices=[
                    ("No Experience", "No Experience"),
                    ("1 Year", "One Year"),
                    ("2 Years", "Two Years"),
                    ("3 Years+", "Three Years Above"),
                ],
                default="No Experience",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="industry",
            field=models.CharField(
                choices=[
                    ("Information Technology", "Informationtechnology"),
                    ("Software Development", "Softwaredevelopment"),
                    ("Business", "Business"),
                    ("Banking", "Banking"),
                    ("Education", "Education"),
                    ("Telecommunication", "Telecommunication"),
                    ("Others", "Others"),
                ],
                default="Business",
                max_length=30,
            ),
        ),
    ]
