# Generated by Django 4.1.4 on 2022-12-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0004_alter_job_experience_alter_job_industry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="experience",
            field=models.CharField(
                choices=[
                    ("No Experience", "No Experience"),
                    ("1 Year", "One Year"),
                    ("2 Years", "Two Years"),
                    ("3 years plus", "Three Years Above"),
                ],
                default="No Experience",
                max_length=20,
            ),
        ),
    ]
